insert into SECURITY_USER (USER_ID, USER_NAME, USER_STAFF_ID, USER_EMAIL_ADDRESS, LAST_UPDATED_DATETIME, LAST_UPDATED_USER_ID, VERSION, RECORD_STATUS)
values(1, 'root', '00000000', 'root@opas.com', now(), 0, 0, 0);

insert into SECURITY_USER (USER_ID, USER_NAME, USER_STAFF_ID, USER_EMAIL_ADDRESS, LAST_UPDATED_DATETIME, LAST_UPDATED_USER_ID, VERSION, RECORD_STATUS)
values(2, 'root', 'sunnytong', 'sunnytong@opas.com', now(), 1, 0, 0);

insert into SECURITY_USER (USER_ID, USER_NAME, USER_STAFF_ID, USER_EMAIL_ADDRESS, LAST_UPDATED_DATETIME, LAST_UPDATED_USER_ID, VERSION, RECORD_STATUS)
values(3, 'root', 'jackccchau', 'jackccchau@opas.com', now(), 1, 0, 0);

insert into SECURITY_USER (USER_ID, USER_NAME, USER_STAFF_ID, USER_EMAIL_ADDRESS, LAST_UPDATED_DATETIME, LAST_UPDATED_USER_ID, VERSION, RECORD_STATUS)
values(4, 'root', 'simonpwchau', 'simonpwchau@opas.com', now(), 1, 0, 0);


insert into ORGANIZATION (ORGANIZATION_ID, ORGANIZATION_ACRONYM, ORGANIZATION_NAME, BIC_CODE, COUNTRY_CODE, GROUP_MEMBER_ABBR, BRANCH_NO, LAST_UPDATED_DATETIME, LAST_UPDATED_USER_ID, VERSION, RECORD_STATUS)
values(1, 'XXXXHKH', 'XXXX Hong Kong', 'XXXXHKHH', 'HK', 'XXXX', 576, now(), 0, 0, 0);


insert into TRADE_WORKFLOW_CONFIG(TRADE_WORKFLOW_CONFIG_ID, ORGANIZATION_ID, TRADE_CLASS_NAME, CURRENT_TRADE_ACTION, CURRENT_TRADE_STATUS, NEXT_TRADE_ACTION, NEXT_TRADE_STATUS, STP_FLAG, LAST_UPDATED_DATETIME, LAST_UPDATED_USER_ID, RECORD_STATUS, VERSION)
values(1, 1, 'model.trade.TradeFxSpot', 'NEW', 'NONE', 'NEW_SSI_PENDING', 1, now(), 0, 0, 0);

insert into TRADE_WORKFLOW_CONFIG(TRADE_WORKFLOW_CONFIG_ID, ORGANIZATION_ID, TRADE_CLASS_NAME, CURRENT_TRADE_ACTION, CURRENT_TRADE_STATUS, NEXT_TRADE_ACTION, NEXT_TRADE_STATUS, STP_FLAG, LAST_UPDATED_DATETIME, LAST_UPDATED_USER_ID, RECORD_STATUS, VERSION)
values(2, 1, 'model.trade.TradeFxSpot', 'PROCESS', 'NEW_SSI_PENDING', 'NEW_EXCEPTION_CHECK', 1, now(), 0, 0, 0);

insert into TRADE_WORKFLOW_CONFIG(TRADE_WORKFLOW_CONFIG_ID, ORGANIZATION_ID, TRADE_CLASS_NAME, CURRENT_TRADE_ACTION, CURRENT_TRADE_STATUS, NEXT_TRADE_ACTION, NEXT_TRADE_STATUS, STP_FLAG, LAST_UPDATED_DATETIME, LAST_UPDATED_USER_ID, RECORD_STATUS, VERSION)
values(3, 1, 'model.trade.TradeFxSpot', 'PROCESS', 'NEW_EXCEPTION_CHECK', 'NORMAL', 1, now(), 0, 0, 0);

insert into TRADE_WORKFLOW_CONFIG(TRADE_WORKFLOW_CONFIG_ID, ORGANIZATION_ID, TRADE_CLASS_NAME, CURRENT_TRADE_ACTION, CURRENT_TRADE_STATUS, NEXT_TRADE_ACTION, NEXT_TRADE_STATUS, STP_FLAG, LAST_UPDATED_DATETIME, LAST_UPDATED_USER_ID, RECORD_STATUS, VERSION)
values(4, 1, 'model.trade.TradeFxSpot', 'AMEND', 'NORMAL', 'AMEND_PENDING', 0, now(), 0, 0, 0);

insert into TRADE_WORKFLOW_CONFIG(TRADE_WORKFLOW_CONFIG_ID, ORGANIZATION_ID, TRADE_CLASS_NAME, CURRENT_TRADE_ACTION, CURRENT_TRADE_STATUS, NEXT_TRADE_ACTION, NEXT_TRADE_STATUS, STP_FLAG, LAST_UPDATED_DATETIME, LAST_UPDATED_USER_ID, RECORD_STATUS, VERSION)
values(5, 1, 'model.trade.TradeFxSpot', 'AMEND_PENDING', 'PROCESS', 'NORMAL', 0, now(), 0, 0, 0);

insert into TRADE_WORKFLOW_CONFIG(TRADE_WORKFLOW_CONFIG_ID, ORGANIZATION_ID, TRADE_CLASS_NAME, CURRENT_TRADE_ACTION, CURRENT_TRADE_STATUS, NEXT_TRADE_ACTION, NEXT_TRADE_STATUS, STP_FLAG, LAST_UPDATED_DATETIME, LAST_UPDATED_USER_ID, RECORD_STATUS, VERSION)
values(5, 1, 'model.trade.TradeFxSpot', 'AMEND_PENDING', 'CANCEL', 'CANCEL_PENDING', 0, now(), 0, 0, 0);

insert into TRADE_WORKFLOW_CONFIG(TRADE_WORKFLOW_CONFIG_ID, ORGANIZATION_ID, TRADE_CLASS_NAME, CURRENT_TRADE_ACTION, CURRENT_TRADE_STATUS, NEXT_TRADE_ACTION, NEXT_TRADE_STATUS, STP_FLAG, LAST_UPDATED_DATETIME, LAST_UPDATED_USER_ID, RECORD_STATUS, VERSION)
values(5, 1, 'model.trade.TradeFxSpot', 'CANCEL_PENDING', 'PROCESS', 'CANCEL_EXCEPTIONG_CHECK', 0, now(), 0, 0, 0);

insert into TRADE_WORKFLOW_CONFIG(TRADE_WORKFLOW_CONFIG_ID, ORGANIZATION_ID, TRADE_CLASS_NAME, CURRENT_TRADE_ACTION, CURRENT_TRADE_STATUS, NEXT_TRADE_ACTION, NEXT_TRADE_STATUS, STP_FLAG, LAST_UPDATED_DATETIME, LAST_UPDATED_USER_ID, RECORD_STATUS, VERSION)
values(5, 1, 'model.trade.TradeFxSpot', 'CANCEL_EXCEPTIONG_CHECK', 'PROCESS', 'CANCELLED', 0, now(), 0, 0, 0);

insert into TRADE_WORKFLOW_CONFIG(TRADE_WORKFLOW_CONFIG_ID, ORGANIZATION_ID, TRADE_CLASS_NAME, CURRENT_TRADE_ACTION, CURRENT_TRADE_STATUS, NEXT_TRADE_ACTION, NEXT_TRADE_STATUS, STP_FLAG, LAST_UPDATED_DATETIME, LAST_UPDATED_USER_ID, RECORD_STATUS, VERSION)
values(5, 1, 'model.trade.TradeFxSpot', 'NEW_SSI_PENDING', 'CANCEL', 'CANCEL_PENDING', 0, now(), 0, 0, 0);

insert into TRADE_WORKFLOW_CONFIG(TRADE_WORKFLOW_CONFIG_ID, ORGANIZATION_ID, TRADE_CLASS_NAME, CURRENT_TRADE_ACTION, CURRENT_TRADE_STATUS, NEXT_TRADE_ACTION, NEXT_TRADE_STATUS, STP_FLAG, LAST_UPDATED_DATETIME, LAST_UPDATED_USER_ID, RECORD_STATUS, VERSION)
values(5, 1, 'model.trade.TradeFxSpot', 'NEW_EXCEPTION_CHECK', 'CANCEL', 'CANCEL_PENDING', 0, now(), 0, 0, 0);

insert into TRADE_WORKFLOW_CONFIG(TRADE_WORKFLOW_CONFIG_ID, ORGANIZATION_ID, TRADE_CLASS_NAME, CURRENT_TRADE_ACTION, CURRENT_TRADE_STATUS, NEXT_TRADE_ACTION, NEXT_TRADE_STATUS, STP_FLAG, LAST_UPDATED_DATETIME, LAST_UPDATED_USER_ID, RECORD_STATUS, VERSION)
values(5, 1, 'model.trade.TradeFxSpot', 'NORMAL', 'MATURE', 'MATURED', 0, now(), 0, 0, 0);

